### ISSUE TITLE
Unexpected racc error thrown

### ISSUE THREAD

**Issue by wvengen** [masa16/phys-units#2]
When phys-units encounters an unrecognised unit, it throws `Phys::UnitError`.
But on certain strings, a `Racc::ParseError` is thrown, I found on real-world data in production.

Wouldn't it be better to wrap `Racc::ParseError` in a `Phys::UnitError`?

``` ruby
Phys::Unit["i"]
# Phys::UnitError: Undefined unit: "i"
# from .../gems/phys-units-0.9.8/lib/phys/units/unit_class.rb:69:in `word'

Phys::Unit["~"]
# Racc::ParseError: 
# parse error on value "~" (error)
# from .../ruby/2.2.0/racc/parser.rb:527:in `on_error'
```

**Comment by masa16** [comment]
Thank you for suggestion. This patch will convert ParseError into UnitError.
https://github.com/masa16/phys-units/commit/4411598d5d5079b1de39ceb753f2a038fbb7be88

**Comment by wvengen** [comment]
Wow, that's fast! And thanks for releasing an updated gem right away :+1:
And it works
```ruby
Phys::Unit["~"]
# Phys::UnitError: parse error on value "~" (error)
# 	from .../gems/phys-units-0.9.9/lib/phys/units/unit_class.rb:79:in `rescue in parse'
# 	from .../gems/phys-units-0.9.9/lib/phys/units/unit_class.rb:77:in `parse'
```
